### ISSUE TITLE
Support for Mikrotik devices

### ISSUE THREAD

**Issue by abitrolly** [inexio/NESi#7]
Does Mikrotik devices fit the project scope? I know they are providing virtual machines, but these need some kind of virtual network stuff to work with.

I am trying to design and debug interactions in a local hackerspace network https://github.com/minsk-hackerspace/spynet/ Not only for update diagrams that constantly get out of sync, but also to debug issues, such as IPSec connections.

**Comment by zatroa** [comment]
Currently the CLI simulation of Mikrotik devices is not supported. But you are welcome to include it with a pull request. We will be happy to help you if you have any questions about the implementation.

**Comment by abitrolly** [comment]
Does that mean that it is possible to emulate with https://github.com/inexio/NESi-UI ?

There are ISO files available from https://mikrotik.com/software but I have no idea how to use them and configure VM devices to match real hardware.

**Comment by zatroa** [comment]
NESi-UI is a webinterface for NESi.

NESi does not work with emulated devices. NESi simulates the CLI behaviour of network devices.
maybe you are looking for projects like GNS3 or eve-ng which work with emulation / virtualization of network devices.

**Comment by abitrolly** [comment]
I hoped that NEXi is a full simulator for network devices, not just CLI. Like GNS3.
